server.port=8080

spring.datasource.url=jdbc:postgresql://team-db:5432/team_db
spring.datasource.username=admin
spring.datasource.password=parola_secreta

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.jackson.serialization.write-dates-as-timestamps=false

management.endpoints.web.exposure.include=health